sudo: required

services:
  - docker

install:
  - docker build -t eoslocal/demux ./services/demux
  - docker build -t eoslocal/frontend ./services/frontend

script:
  - docker run eoslocal/demux yarn lint
  - docker run eoslocal/frontend yarn lint
