version: "3"

services:

  # only required for dev
  eosiodev:
    build:
      context: ./services/eos-dev
      dockerfile: Dockerfile
    image: eosdapp/eosdev
    stop_grace_period: 3m0s
    command: /opt/eosio/bin/nodeos --config-dir /opt/application/config --data-dir /root/.local/share -e
    ports:
      - "8888:8888"
      - "9830:9876"
    volumes:
      - eosiodev-data-volume:/root/.local/share
      - ./services/eos-dev:/opt/application

  fullnode:
    image: eosio/eos:v1.2.4
    command: nodeosd.sh --http-alias=fullnode:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
    #--genesis-json /opt/eosio/bin/genesis.json
    stop_grace_period: 3m0s
    ports:
      - "8840:8888"
      - "9840:9876"
    depends_on:
      - mongodb
      - eosiodev
    volumes:
      - "fullnode-data-volume:/opt/eosio/bin/data-dir"
      - "./services/eos-node/config-full-node.ini:/opt/eosio/bin/data-dir/config.ini"
      # - "./services/eos-node/config-main-node.ini:/opt/eosio/bin/data-dir/config.ini"
      # - "./services/eos-node/mainnet-genesis.json:/opt/eosio/bin/genesis.json"
    networks:
      eos-local:
        aliases:
          - local.eosio.cr
    environment:
      - VIRTUAL_HOST=local.eosio.cr
      - VIRTUAL_PORT=8888

  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongodb-data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      eos-local:
        aliases:
          - mongodb.local.eosio.cr

  mongo-admin:
    image: mrvautin/adminmongo:latest
    ports:
      - '8082:8082'
    environment:
      - PORT=8082
      - CONN_NAME=smartgate-db
      - DB_HOST=mongodb.local.eosio.cr
      - VIRTUAL_HOST=admin-mongo.local.eosio.cr
      - VIRTUAL_PORT=8082
    depends_on:
      - mongodb
    networks:
      eos-local:
        aliases:
          - admin-mongo.local.eosio.cr

  wallet:
    image: eosio/eos-dev
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=127.0.0.1:8900
    hostname: keosd
    links:
      - fullnode
    volumes:
      - keosd-data-volume:/opt/eosio/bin/data-dir
    stop_grace_period: 10m
    networks:
      - eos-local

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - eos-local

volumes:
  fullnode-data-volume:
    external: true
  keosd-data-volume:
    external: true
  mongodb-data-volume:
    external: true
  eosiodev-data-volume:
    external: true

networks:
  eos-local:
